# Your name and what you do
name: Joe Rowing
bio: Physics Education

description: Joe Rowing's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://jrowing.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
# twitter: mytwitter
linkedin: jrowing
github: jrowing
email: joe@jrowing.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
medium: JRowing
# vimeo: myvimeo
# lanyrd: mylanyrd
# bandcamp: taleriverrowing
geogebra: joerowing

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - Leadership and Management:
    - Leading teams in educational settings, including as Deputy Headteacher.
    - Establishing and managing academic programmes and institutions (e.g., Exeter Maths School).
    - Strategic planning and implementation of school initiatives.","Mentoring and professional development for staff.
    - Teaching and Curriculum Design
        - Expertise in teaching Physics, particularly at A Level.
        - Curriculum development for STEM subjects, including Mathematics and Physics.
        - Delivering enrichment programmes (e.g., Exeter Maths School Physics Programme).
        - Designing interactive and engaging lessons to inspire student learning.
    - STEM Expertise
        - Deep knowledge of Physics and its real-world applications.
        - Promoting STEM careers and fostering a love for science among students.
        - Experience with advanced topics, problem-solving, and experimental techniques.
    - Professional Development
        - Coaching and mentoring teachers to improve subject delivery.
        - Leading workshops and sharing best practices in Physics education.
        - Supporting colleagues with tailored guidance and resources.
    - Communication and Collaboration
        - Building strong partnerships with universities, industries, and educational organisations.
        - Clear and effective communication with diverse stakeholders, including students, staff, parents, and partners.
        - Collaborative team working in both leadership and teaching capacities.
    - Resource Development
        - Creating and delivering teaching and learning materials (e.g., for Edexcel A Level Physics).
        - Innovating with educational tools and technology to enhance learning.
    - Project Management
        - Coordinating and delivering complex educational projects (e.g., NEEMO 16 Education Project).
        - Managing events, workshops, and programmes for student engagement.
    - International Perspective
        - Experience and interest in education in a global context, with a focus on international opportunities.
    - Additional Skills
        - Analytical and problem-solving abilities.
        - Adaptability to new challenges and settings.
        - Passion for fostering academic excellence and innovation.

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    PhysNotes:
        name: Physics Notes
        description: Complete textbook/notes for the A-level Physics course.
        url: https://github.com/jrowing/EMS-Physics-Notes
    IoP:
        name: Institute of Physics Coach
        description: Provided expert guidance and support to teachers, helping to improve the quality of physics education and student outcomes locally and Nationally. Drawing on extensive subject knowledge and teaching experience to developed and delivered professional development sessions, share best practices, and offered tailored mentoring to colleagues. Areas of particular focus included fostering confidence and excellence in physics teaching, improving the gender balance and enabling teachers to inspire and engage students while promoting a deeper understanding of the subject and its real-world applications.
        url: https://www.iop.org/education
    EMS:
        name: Exeter Maths School
        description: Instrumental in the establishment of Exeter Maths School, a specialist sixth form college for talented mathematicians aged 16-19. As part of the founding team, Joe played a key role in designing and implementing the curriculum, the safeguarding, pastoral and behaviour policies, careers and university progression. Also Establishing the boarding provision, establishing the physics lab, building strong partnerships with local universities and industries, and fostering a culture of academic excellence and innovation. Leadership contributed to the school’s success in providing an outstanding education, nurturing students’ passion for STEM, and achieving national recognition as a centre of excellence for mathematics and physics.
        url: https://exetermathematicsschool.ac.uk/
    Neemo16:
        name: NEEMO 16
        description: The NEEMO 16 Education Project is an educational initiative designed to engage students with science, technology, engineering, and mathematics (STEM) through the lens of space exploration and underwater research. Developed as part of NASA’s Extreme Environment Mission Operations (NEEMO), this project leverages the unique environment of underwater habitats to simulate the challenges of space missions.
        url: https://www.youtube.com/watch?v=tmdgJ7FUvuc&list=PL50D3F281AF1788F3&ab_channel=NASAanalogTV
    PhysNotes:
        name: Physics Notes
        description: Complete textbook/notes for the A-level Physics course.
        url: https://github.com/jrowing/EMS-Physics-Notes
    Hodder:
        name: Edexcel A Level Physics Teaching and Learning Resources
        description: Textbook authoring and production of Teaching and Learning Resources for the Edexcel A Level Physics course. Published by Hachette Learning (Hodder)
        url: https://openlibrary.org/books/OL37962284M/Edexcel_a_Level_Physics_2_Teaching_and_Learning_Resources
    

# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
   - jekyll-seo-tag  

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
