# Your name and what you do
name: Joe Rowing
bio: Physics Education

description: Joe Rowing's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://jrowing.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
# twitter: mytwitter
linkedin: jrowing
github: jrowing
email: joe@jrowing.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
medium: JRowing
# vimeo: myvimeo
# lanyrd: mylanyrd
# bandcamp: taleriverrowing
geogebra: joerowing

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - Physics
    - Python
    - Curriculum planning
    - School Leadership
    - Teacher Training
    - Education Theory

# do you want to display a projects section? true or false
projects: false

# do you want to display a projects section? true or false
projects: false

# add your projects here
project-list:
    Exeter-Maths-School:
        name: Exeter Maths School
        description: Instrumental in the establishment of Exeter Maths School, a specialist sixth form college for talented mathematicians aged 16-19. 
        url: https://exetermathematicsschool.ac.uk/
    GCSE-Physics:
        name: GCSE Physics Enhancement programme
        description:  This programme offers a unique blend of problem-solving activities, and enrichment sessions, encouraging students to explore advanced concepts and develop their analytical and experimental skills.
        url:
    IoP-Physics-Coach:
        name: IoP Physics Coach
        description: As a Physics Coach, I provided expert guidance and support to teachers, helping to improve the quality of physics education and student outcomes. 
        url:
    Hodder:
        name: Edexcel A Level Physics Teaching and Learning Resources
        description:  A suite of educational materials designed to support teachers and students in delivering and studying the Edexcel A Level Physics course.
        url: https://openlibrary.org/books/OL37962284M/Edexcel_a_Level_Physics_2_Teaching_and_Learning_Resources
     NASA:
        name: NASA NEEMO 16 project
        description:  An educational initiative designed to engage students with science, technology, engineering, and mathematics (STEM) through the lens of space exploration and underwater research. 
        url:
# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
   - jekyll-seo-tag  

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
