title: Joe Rowing
description: Educator, Physicist, Explorer
baseurl: ""
url: "https://jrowing.com"
permalink: /:categories/:title/

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
