project:
  type: website
  output-dir: docs
resources:
  - CNAME
website:
  title: "JRowing.com"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jrowing
      - icon: twitter
        href: https://twitter.com/jrowing
include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "favicon.ico" />  
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
  
editor: visual

