project:
  type: website

website:
  title: "JRowing.com"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jrowing
      - icon: twitter
        href: https://twitter.com/jrowing
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css

editor: visual

